[package]
name = "vexide-async"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "The async executor at the core of vexide"
keywords = ["Robotics", "bindings", "async", "vex", "v5"]
categories = [
    "no-std",
    "science::robotics",
    "Asynchronous"
]
repository = "https://github.com/vexide/vexide"
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
    "Tropical"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-task = { version = "4.5.0", default-features = false }
vexide-core = { version = "0.3.0", path = "../vexide-core" }
waker-fn = "1.1.1"
vex-sdk = "0.17.0"
critical-section = { version = "1.1.2", features = ["restore-state-bool"] }
no_std_io = { version = "0.6.0", features = ["alloc"] }

[lints]
workspace = true
