[build]
target = "armv7a-vex-v5"

[target.wasm32-unknown-unknown]
rustflags = ["-Clink-arg=--export-memory", "-Clink-arg=--import-table"]

[unstable]
build-std = ["std"]
build-std-features = ["compiler-builtins-mem"]
