[package]
name = "vexide"
version = "0.3.0"
edition = "2021"
description = "async/await powered Rust library for VEX V5 Brains"
keywords = ["Robotics", "bindings", "vex", "v5"]
categories = ["os", "api-bindings", "no-std", "science::robotics"]
license = "MIT"
repository = "https://github.com/vexide/vexide"
readme = "../../README.md"
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
    "Tropical"
]
rust-version = "1.75.0"

[package.metadata.v5]
slot = 1
icon = "cool-x"
compress = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vexide-runtime = { version = "0.3.0", path = "../vexide-runtime", optional = true }
vexide-devices = { version = "0.3.0", path = "../vexide-devices", optional = true, features = ["std"] }
vexide-graphics = { version = "0.1.2", path = "../vexide-graphics", optional = true }
vexide-macro = { version = "0.2.0", path = "../vexide-macro", optional = true }
vex-sdk = "0.17.0"

[features]
default = ["rt", "devices", "macro"]

macro = ["dep:vexide-macro", "rt", "devices"]

rt = ["dep:vexide-runtime"]

devices = ["dep:vexide-devices"]

graphics = ["dep:vexide-graphics"]
slint = ["vexide-graphics/slint", "graphics"]
embedded-graphics = ["vexide-graphics/embedded-graphics", "graphics"]

dangerous_motor_tuning = ["vexide-devices/dangerous_motor_tuning"]
smart_leds_trait = ["vexide-devices/smart_leds_trait"]
