[package]
name = "vexide-graphics"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Graphics driver implementations for vexide"
keywords = ["Robotics", "graphics", "vex", "v5"]
authors = [
    "vexide",
    "Gavin Niederman <gavinniederman@gmail.com>",
    "doinkythederp <doinkythederp@icloud.com>",
    "Tropical"
]
repository = "https://github.com/vexide/vexide"

[dependencies]
embedded-graphics-core = { version = "0.4.0", optional = true }
slint = { version = "1.5.1", default-features = false, optional = true, features = ["compat-1-2", "unsafe-single-threaded", "libm", "renderer-software"] }
vex-sdk = "0.17.0"
vexide-runtime = { version = "0.3.0", path = "../vexide-runtime" }
vexide-devices = { version = "0.3.0", path = "../vexide-devices" }

[lints]
workspace = true

[features]
default = []

embedded-graphics = ["dep:embedded-graphics-core"]
slint = ["dep:slint"]
